version: 0.2
phases:
  install:
    commands:
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
      - unzip packer.zip
  build:
    commands:
      - ./packer build web-server.json